# What is PyTorch?

It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

## Getting Started

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch
import numpy as np

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-5.7709e-30,  4.5622e-41, -5.7709e-30],
        [ 4.5622e-41,  0.0000e+00,  0.0000e+00],
        [-1.1207e+03,  1.0576e-15, -8.9850e-35],
        [ 4.5622e-41, -2.3072e-29,  4.5622e-41],
        [ 6.4537e-04,  7.7555e+26,  0.0000e+00]])


Construct a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0753, 0.0048, 0.2542],
        [0.7512, 0.0834, 0.3091],
        [0.7102, 0.4677, 0.8464],
        [0.1575, 0.2310, 0.9475],
        [0.6535, 0.9700, 0.8546]])


  Construct a matrix filled zeros and of dtype `int64`:

In [4]:
x = torch.zeros(5, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [15]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1958,  0.4758,  0.2651],
        [ 0.2743, -0.3481,  0.2082],
        [ 1.2218,  1.5582, -0.3998],
        [-0.0380, -2.4893, -0.4970],
        [ 0.2977, -1.8162, -0.1032]])


Get its size:

In [16]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


#### note
     torch.Size is in fact a tuple, so it supports all tuple operations.

### Operations

Operations work as expected

In [17]:
print("Reminder, x=")
print(x)
print("Then, x+y=")
y = torch.rand(5, 3)
print(x + y)

Reminder, x=
tensor([[ 1.1958,  0.4758,  0.2651],
        [ 0.2743, -0.3481,  0.2082],
        [ 1.2218,  1.5582, -0.3998],
        [-0.0380, -2.4893, -0.4970],
        [ 0.2977, -1.8162, -0.1032]])
Then, x+y=
tensor([[ 1.7969,  0.8881,  0.3966],
        [ 1.1199,  0.1917,  1.0532],
        [ 1.9223,  1.7509,  0.0574],
        [ 0.7878, -1.6876, -0.1890],
        [ 1.1249, -0.9070,  0.3610]])


n00b test :

In [30]:
i = torch.ones(5, 3, dtype=torch.int64)
#i = torch.zeros(5, 3, dtype=torch.int64)
print("i = ")
print(i)
j = 2*i
print("j = ")
print(j)
print("Addition de tenseurs : i+j = ")
print(i+j)

i = 
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
j = 
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])
Addition de tenseurs : i+j = 
tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])


Addition: in-place

In [31]:
y += x
print(y)

tensor([[ 1.7969,  0.8881,  0.3966],
        [ 1.1199,  0.1917,  1.0532],
        [ 1.9223,  1.7509,  0.0574],
        [ 0.7878, -1.6876, -0.1890],
        [ 1.1249, -0.9070,  0.3610]])


#### note
    Any operation that mutates a tensor in-place is post-fixed with an _.
    For example: x.copy_(y), x.t_(), will change x.

You can use standard NumPy-like indexing with all bells and whistles!

In [ ]:
print(x[:, 1])

Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:

In [ ]:
x = torch.randn(4, 4)
x

Numpy-style reshaping 

In [ ]:
x.reshape(16)

In [ ]:
x.reshape(-1, 8)

If you have a one element tensor, use ``.item()`` to get the value as a Python number

In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

**Read later:**


100+ Tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random numbers, etc.,
are described
[here](http://pytorch.org/docs/torch).

## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch `Tensor` and NumPy `array` will share their underlying memory
locations, and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [ ]:
a = torch.ones(5)
print(a)

In [ ]:
b = a.numpy()
print(b)

See how the numpy array changed in value.

In [ ]:
a += 1
print(a)
print(b)

### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

**Exercices:**

- L2-normalize the rows of a matrix

- generate a random matrix then set the diagonal of a matrix to 0

- generate a random matrix and make a matrix with 3x4 tiles of that matrix

All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

## CUDA Tensors

Tensors can be moved onto any device using the ``.to`` method.

In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xy
\end{align}