# What is PyTorch?

It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

## Getting Started

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch
import numpy as np

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[3.8040e-16, 4.5734e-41, 2.5485e-37],
        [0.0000e+00,        nan, 4.5734e-41],
        [7.6194e+31, 1.5564e+28, 1.8484e+31],
        [1.8370e+25, 1.4603e-19, 2.7517e+12],
        [7.5338e+28, 3.0313e+32, 6.3828e+28]])


Construct a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4563, 0.7603, 0.0392],
        [0.1805, 0.8185, 0.0520],
        [0.0221, 0.7281, 0.6809],
        [0.0620, 0.6552, 0.8297],
        [0.5807, 0.4249, 0.5968]])


  Construct a matrix filled zeros and of dtype `int64`:

In [4]:
x = torch.zeros(5, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1606,  1.8335, -0.9846],
        [ 0.3379, -0.4929, -1.8270],
        [ 0.5049, -0.0134, -0.0212],
        [-0.7508,  0.2236,  0.1841],
        [-1.9939, -0.8284, -0.6280]])


Get its size:

In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


#### note
     torch.Size is in fact a tuple, so it supports all tuple operations.

### Operations

Operations work as expected

In [8]:
print("Reminder, x=")
print(x)
print("Then, x+y=")
y = torch.rand(5, 3)
print(x + y)

Reminder, x=
tensor([[-0.1606,  1.8335, -0.9846],
        [ 0.3379, -0.4929, -1.8270],
        [ 0.5049, -0.0134, -0.0212],
        [-0.7508,  0.2236,  0.1841],
        [-1.9939, -0.8284, -0.6280]])
Then, x+y=
tensor([[ 0.0091,  2.2915, -0.2774],
        [ 1.2052, -0.1954, -1.3035],
        [ 1.3442,  0.0577,  0.6512],
        [-0.2713,  1.1621,  0.3763],
        [-1.1464, -0.0456, -0.0404]])


n00b test :

In [9]:
i = torch.ones(5, 3, dtype=torch.int64)
#i = torch.zeros(5, 3, dtype=torch.int64)
print("i = ")
print(i)
j = 2*i
print("j = ")
print(j)
print("Addition de tenseurs : i+j = ")
print(i+j)

i = 
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
j = 
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])
Addition de tenseurs : i+j = 
tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])


Addition: in-place

In [10]:
y += x
print(y)

tensor([[ 0.0091,  2.2915, -0.2774],
        [ 1.2052, -0.1954, -1.3035],
        [ 1.3442,  0.0577,  0.6512],
        [-0.2713,  1.1621,  0.3763],
        [-1.1464, -0.0456, -0.0404]])


#### note
    Any operation that mutates a tensor in-place is post-fixed with an _.
    For example: x.copy_(y), x.t_(), will change x.

You can use standard NumPy-like indexing with all bells and whistles!

In [12]:
print("Reminder, x=")
print(x)

Reminder, x=
tensor([[-0.1606,  1.8335, -0.9846],
        [ 0.3379, -0.4929, -1.8270],
        [ 0.5049, -0.0134, -0.0212],
        [-0.7508,  0.2236,  0.1841],
        [-1.9939, -0.8284, -0.6280]])


In [13]:
print(x[:, 1])

tensor([ 1.8335, -0.4929, -0.0134,  0.2236, -0.8284])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:

In [14]:
x = torch.randn(4, 4)
x

tensor([[-0.3655, -1.2916, -1.6821, -0.9715],
        [ 1.6051,  0.4264,  0.1504,  1.0217],
        [-0.6884, -1.2190, -1.7144,  1.0528],
        [-0.3305, -1.3309,  0.6351, -1.4633]])

Numpy-style reshaping 

In [15]:
x.reshape(16)

tensor([-0.3655, -1.2916, -1.6821, -0.9715,  1.6051,  0.4264,  0.1504,  1.0217,
        -0.6884, -1.2190, -1.7144,  1.0528, -0.3305, -1.3309,  0.6351, -1.4633])

The -1 value used in the reshape function lets reshape() decide which dimension should be chosed.

In [19]:
x.reshape(-1, 8)

tensor([[-0.3655, -1.2916, -1.6821, -0.9715,  1.6051,  0.4264,  0.1504,  1.0217],
        [-0.6884, -1.2190, -1.7144,  1.0528, -0.3305, -1.3309,  0.6351, -1.4633]])

In [17]:
print(x)

tensor([[-0.3655, -1.2916, -1.6821, -0.9715],
        [ 1.6051,  0.4264,  0.1504,  1.0217],
        [-0.6884, -1.2190, -1.7144,  1.0528],
        [-0.3305, -1.3309,  0.6351, -1.4633]])


In [29]:
x.reshape(-1,4)

tensor([[-0.3655, -1.2916, -1.6821, -0.9715],
        [ 1.6051,  0.4264,  0.1504,  1.0217],
        [-0.6884, -1.2190, -1.7144,  1.0528],
        [-0.3305, -1.3309,  0.6351, -1.4633]])

If you have a one element tensor, use ``.item()`` to get the value as a Python number

In [30]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2727])
-0.27269622683525085


**Read later:**


100+ Tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random numbers, etc.,
are described
[here](http://pytorch.org/docs/torch).

## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch `Tensor` and NumPy `array` will share their underlying memory
locations, and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [31]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [32]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.

In [33]:
a += 1
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[ 2.  2.  2.  2.  2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [34]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**Exercices:**

- L2-normalize the rows of a matrix

- generate a random matrix then set the diagonal of a matrix to 0

- generate a random matrix and make a matrix with 3x4 tiles of that matrix

In [45]:
x = torch.randn(2,2)
print(x)
print(1/(1-np.exp(-x)))
print(torch.normalize(x))

tensor([[0.2895, 1.4686],
        [0.5316, 0.7657]])
tensor([[3.9789, 1.2991],
        [2.4252, 1.8692]])


AttributeError: module 'torch' has no attribute 'normalize'

In [46]:
x = torch.randn(2,2)
print(x)
print(x/np.absolute(x))

tensor([[-0.2021, -0.3115],
        [-1.1010,  0.4234]])
tensor([[-1., -1.],
        [-1.,  1.]])


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

## CUDA Tensors

Tensors can be moved onto any device using the ``.to`` method.

In [36]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else: print("Cuda is not available. Sorry :(")

Cuda is not available. Sorry :(


\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xy
\end{align}