# What is PyTorch?

It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

## Getting Started

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [2]:
from __future__ import print_function
import torch
import numpy as np

Construct a 5x3 matrix, uninitialized:

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


Construct a randomly initialized matrix:

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1078, 0.3475, 0.4197],
        [0.3849, 0.1164, 0.2754],
        [0.3612, 0.7316, 0.4807],
        [0.1942, 0.2750, 0.8398],
        [0.4138, 0.9456, 0.6343]])


  Construct a matrix filled zeros and of dtype `int64`:

In [5]:
x = torch.zeros(5, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3990, -1.7817,  1.0581],
        [ 0.8086,  0.5876, -0.7118],
        [ 0.5311,  1.1322, -0.3166],
        [ 0.3908,  0.6916,  0.5891],
        [ 1.7525,  1.2948,  0.6532]])


Get its size:

In [8]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


#### note
     torch.Size is in fact a tuple, so it supports all tuple operations.

### Operations

Operations work as expected

In [9]:
print("Reminder, x=")
print(x)
print("Then, x+y=")
y = torch.rand(5, 3)
print(x + y)

Reminder, x=
tensor([[ 0.3990, -1.7817,  1.0581],
        [ 0.8086,  0.5876, -0.7118],
        [ 0.5311,  1.1322, -0.3166],
        [ 0.3908,  0.6916,  0.5891],
        [ 1.7525,  1.2948,  0.6532]])
Then, x+y=
tensor([[ 0.5135, -1.5622,  1.6537],
        [ 1.1513,  1.3256,  0.0167],
        [ 1.3188,  1.7432, -0.2739],
        [ 0.7784,  1.2808,  1.2971],
        [ 2.2414,  1.5898,  1.5046]])


n00b test :

In [10]:
i = torch.ones(5, 3, dtype=torch.int64)
#i = torch.zeros(5, 3, dtype=torch.int64)
print("i = ")
print(i)
j = 2*i
print("j = ")
print(j)
print("Addition de tenseurs : i+j = ")
print(i+j)

i = 
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
j = 
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])
Addition de tenseurs : i+j = 
tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])


Addition: in-place

In [11]:
y += x
print(y)

tensor([[ 0.5135, -1.5622,  1.6537],
        [ 1.1513,  1.3256,  0.0167],
        [ 1.3188,  1.7432, -0.2739],
        [ 0.7784,  1.2808,  1.2971],
        [ 2.2414,  1.5898,  1.5046]])


#### note
    Any operation that mutates a tensor in-place is post-fixed with an _.
    For example: x.copy_(y), x.t_(), will change x.

You can use standard NumPy-like indexing with all bells and whistles!

In [12]:
print("Reminder, x=")
print(x)

Reminder, x=
tensor([[ 0.3990, -1.7817,  1.0581],
        [ 0.8086,  0.5876, -0.7118],
        [ 0.5311,  1.1322, -0.3166],
        [ 0.3908,  0.6916,  0.5891],
        [ 1.7525,  1.2948,  0.6532]])


In [13]:
print(x[:, 1])

tensor([-1.7817,  0.5876,  1.1322,  0.6916,  1.2948])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:

In [14]:
x = torch.randn(4, 4)
x

tensor([[ 0.2304, -1.0242,  0.7444,  1.7712],
        [ 0.4485, -0.1957, -0.4390, -1.1813],
        [-0.0327,  0.7275, -0.1344, -1.0599],
        [ 0.1339,  2.1271, -1.1565, -0.0394]])

Numpy-style reshaping 

In [15]:
x.reshape(16)

tensor([ 0.2304, -1.0242,  0.7444,  1.7712,  0.4485, -0.1957, -0.4390, -1.1813,
        -0.0327,  0.7275, -0.1344, -1.0599,  0.1339,  2.1271, -1.1565, -0.0394])

The -1 value used in the reshape function lets reshape() decide which dimension should be chosed.

In [16]:
x.reshape(-1, 8)

tensor([[ 0.2304, -1.0242,  0.7444,  1.7712,  0.4485, -0.1957, -0.4390, -1.1813],
        [-0.0327,  0.7275, -0.1344, -1.0599,  0.1339,  2.1271, -1.1565, -0.0394]])

In [17]:
print(x)

tensor([[ 0.2304, -1.0242,  0.7444,  1.7712],
        [ 0.4485, -0.1957, -0.4390, -1.1813],
        [-0.0327,  0.7275, -0.1344, -1.0599],
        [ 0.1339,  2.1271, -1.1565, -0.0394]])


In [18]:
x.reshape(-1,4)

tensor([[ 0.2304, -1.0242,  0.7444,  1.7712],
        [ 0.4485, -0.1957, -0.4390, -1.1813],
        [-0.0327,  0.7275, -0.1344, -1.0599],
        [ 0.1339,  2.1271, -1.1565, -0.0394]])

If you have a one element tensor, use ``.item()`` to get the value as a Python number

In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.8751])
0.8751415014266968


**Read later:**


100+ Tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random numbers, etc.,
are described
[here](http://pytorch.org/docs/torch).

## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch `Tensor` and NumPy `array` will share their underlying memory
locations, and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.

In [22]:
a += 1
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[ 2.  2.  2.  2.  2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**Exercices:**

- L2-normalize the rows of a matrix

- generate a random matrix then set the diagonal of a matrix to 0

- generate a random matrix and make a matrix with 3x4 tiles of that matrix

In [24]:
print("L2-normalize the rows of a matrix :")
#x = torch.randn(2,2)
x = torch.tensor([[5.5, 7], [3, 1.5]])
print(x)
x_norm = torch.nn.functional.normalize(x, 2)
print(x_norm)
#np.absolute(x_norm)

L2-normalize the rows of a matrix :
tensor([[5.5000, 7.0000],
        [3.0000, 1.5000]])
tensor([[0.6178, 0.7863],
        [0.8944, 0.4472]])


In [25]:
print("rand a matrix and set the diagonal to zero : ")

def mask_zero(matrix):
    for i in range(0, 5, 1):
        matrix[i,i]=0
    return matrix



x = torch.randn(5,5)
print(x)
x = mask_zero(x)
print(x)


rand a matrix and set the diagonal to zero : 
tensor([[ 1.2838,  1.1982, -0.0698,  1.2116, -0.4321],
        [-0.0452,  0.0356,  0.2638, -0.4666,  0.2691],
        [ 0.4976, -0.4011,  1.1309, -0.9985, -1.1763],
        [ 0.9796,  0.6229, -0.3024, -0.9417, -0.6245],
        [-2.1866, -0.2474, -0.1308, -0.2325, -0.9463]])
tensor([[ 0.0000,  1.1982, -0.0698,  1.2116, -0.4321],
        [-0.0452,  0.0000,  0.2638, -0.4666,  0.2691],
        [ 0.4976, -0.4011,  0.0000, -0.9985, -1.1763],
        [ 0.9796,  0.6229, -0.3024,  0.0000, -0.6245],
        [-2.1866, -0.2474, -0.1308, -0.2325,  0.0000]])


In [30]:
print("generate a random matrix and make a matrix with 3x4 tiles of that matrix")
x = torch.rand(2, 12)
print(x)
x.reshape(3, 4, -1)

generate a random matrix and make a matrix with 3x4 tiles of that matrix
tensor([[0.2881, 0.3022, 0.9834, 0.0160, 0.4540, 0.2765, 0.3361, 0.0550, 0.7863,
         0.3116, 0.4113, 0.3470],
        [0.6779, 0.6818, 0.3244, 0.7849, 0.6861, 0.0910, 0.2269, 0.4186, 0.2190,
         0.6371, 0.4678, 0.2739]])


tensor([[[0.2881, 0.3022],
         [0.9834, 0.0160],
         [0.4540, 0.2765],
         [0.3361, 0.0550]],

        [[0.7863, 0.3116],
         [0.4113, 0.3470],
         [0.6779, 0.6818],
         [0.3244, 0.7849]],

        [[0.6861, 0.0910],
         [0.2269, 0.4186],
         [0.2190, 0.6371],
         [0.4678, 0.2739]]])

All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

## CUDA Tensors

Tensors can be moved onto any device using the ``.to`` method.

In [36]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else: print("Cuda is not available. Sorry :(")

Cuda is not available. Sorry :(


\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xy
\end{align}