# What is PyTorch?

It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

## Getting Started

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch
import numpy as np

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0.4058, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


Construct a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8453, 0.0225, 0.7032],
        [0.4666, 0.4733, 0.2385],
        [0.4508, 0.6483, 0.7450],
        [0.8252, 0.4650, 0.6511],
        [0.7510, 0.4660, 0.9234]])


  Construct a matrix filled zeros and of dtype `int64`:

In [4]:
x = torch.zeros(5, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1954, -0.7574,  1.4189],
        [-0.5969,  2.1133, -0.0570],
        [ 0.2326,  1.9914, -0.7560],
        [-1.3064,  0.6804,  0.1454],
        [ 1.2856,  0.6422, -0.3733]])


Get its size:

In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


#### note
     torch.Size is in fact a tuple, so it supports all tuple operations.

### Operations

Operations work as expected

In [8]:
print("Reminder, x=")
print(x)
print("Then, x+y=")
y = torch.rand(5, 3)
print(x + y)

Reminder, x=
tensor([[-0.1954, -0.7574,  1.4189],
        [-0.5969,  2.1133, -0.0570],
        [ 0.2326,  1.9914, -0.7560],
        [-1.3064,  0.6804,  0.1454],
        [ 1.2856,  0.6422, -0.3733]])
Then, x+y=
tensor([[-0.0389, -0.3069,  1.5423],
        [ 0.2665,  2.2258,  0.0062],
        [ 0.3332,  2.3575, -0.3397],
        [-1.0857,  1.3085,  0.5044],
        [ 1.3795,  0.8300,  0.5392]])


n00b test :

In [9]:
i = torch.ones(5, 3, dtype=torch.int64)
#i = torch.zeros(5, 3, dtype=torch.int64)
print("i = ")
print(i)
j = 2*i
print("j = ")
print(j)
print("Addition de tenseurs : i+j = ")
print(i+j)

i = 
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
j = 
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])
Addition de tenseurs : i+j = 
tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])


Addition: in-place

In [10]:
y += x
print(y)

tensor([[-0.0389, -0.3069,  1.5423],
        [ 0.2665,  2.2258,  0.0062],
        [ 0.3332,  2.3575, -0.3397],
        [-1.0857,  1.3085,  0.5044],
        [ 1.3795,  0.8300,  0.5392]])


#### note
    Any operation that mutates a tensor in-place is post-fixed with an _.
    For example: x.copy_(y), x.t_(), will change x.

You can use standard NumPy-like indexing with all bells and whistles!

In [11]:
print("Reminder, x=")
print(x)

Reminder, x=
tensor([[-0.1954, -0.7574,  1.4189],
        [-0.5969,  2.1133, -0.0570],
        [ 0.2326,  1.9914, -0.7560],
        [-1.3064,  0.6804,  0.1454],
        [ 1.2856,  0.6422, -0.3733]])


In [12]:
print(x[:, 1])

tensor([-0.7574,  2.1133,  1.9914,  0.6804,  0.6422])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:

In [13]:
x = torch.randn(4, 4)
x

tensor([[-1.2701, -0.2149,  1.1383,  0.1317],
        [-0.4816, -1.2790, -0.6310, -0.6824],
        [-1.1678, -0.4420,  1.3668,  0.4788],
        [-2.0887, -0.2362, -0.5680,  0.8464]])

Numpy-style reshaping 

In [14]:
x.reshape(16)

tensor([-1.2701, -0.2149,  1.1383,  0.1317, -0.4816, -1.2790, -0.6310, -0.6824,
        -1.1678, -0.4420,  1.3668,  0.4788, -2.0887, -0.2362, -0.5680,  0.8464])

The -1 value used in the reshape function lets reshape() decide which dimension should be chosed.

In [16]:
x.reshape(-1, 8)

tensor([[-1.2701, -0.2149,  1.1383,  0.1317, -0.4816, -1.2790, -0.6310, -0.6824],
        [-1.1678, -0.4420,  1.3668,  0.4788, -2.0887, -0.2362, -0.5680,  0.8464]])

In [17]:
print(x)

tensor([[-1.2701, -0.2149,  1.1383,  0.1317],
        [-0.4816, -1.2790, -0.6310, -0.6824],
        [-1.1678, -0.4420,  1.3668,  0.4788],
        [-2.0887, -0.2362, -0.5680,  0.8464]])


In [18]:
x.reshape(-1,4)

tensor([[-1.2701, -0.2149,  1.1383,  0.1317],
        [-0.4816, -1.2790, -0.6310, -0.6824],
        [-1.1678, -0.4420,  1.3668,  0.4788],
        [-2.0887, -0.2362, -0.5680,  0.8464]])

If you have a one element tensor, use ``.item()`` to get the value as a Python number

In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.7689])
-0.7688600420951843


**Read later:**


100+ Tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random numbers, etc.,
are described
[here](http://pytorch.org/docs/torch).

## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch `Tensor` and NumPy `array` will share their underlying memory
locations, and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.

In [22]:
a += 1
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[ 2.  2.  2.  2.  2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**Exercices:**

- L2-normalize the rows of a matrix

- generate a random matrix then set the diagonal of a matrix to 0

- generate a random matrix and make a matrix with 3x4 tiles of that matrix

In [35]:
print("L2-normalize the rows of a matrix :")
#x = torch.randn(2,2)
x = torch.tensor([[5.5, 7], [3, 1.5]])
print(x)
x_norm = torch.nn.functional.normalize(x, 2)
print(x_norm)
#np.absolute(x_norm)

L2-normalize the rows of a matrix :
tensor([[5.5000, 7.0000],
        [3.0000, 1.5000]])
tensor([[0.6178, 0.7863],
        [0.8944, 0.4472]])


In [47]:
print("rand a matrix and set the diagonal to zero : ")
x = torch.randn(5,5)
print(x)
x = mask_zero(x)
print(x)

def mask_zero(matrix):
    for i in range(0, 5, 1):
        matrix[i,i]=0
    return matrix

rand a matrix and set the diagonal to zero : 
tensor([[-2.5582, -0.3713, -1.0078,  1.5412, -0.6107],
        [ 0.4320, -1.6517,  1.2782, -0.5558, -0.2592],
        [ 0.6865,  0.5646,  0.1218,  0.4427, -0.4917],
        [ 1.6706, -1.5233,  0.1027, -0.4048,  0.1709],
        [-0.5535, -0.0694, -1.0203, -0.2788, -0.3101]])


NameError: name 'mask_zero' is not defined

All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

## CUDA Tensors

Tensors can be moved onto any device using the ``.to`` method.

In [36]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else: print("Cuda is not available. Sorry :(")

Cuda is not available. Sorry :(


\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xy
\end{align}